name: build

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - main

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        from:
        - focal
        - jammy
    steps:
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v2

    - name: Configure Buildkit
      uses: docker/setup-buildx-action@v2

    - name: Checkout project
      uses: actions/checkout@v3

    - name: Authenticate with Quay.io
      uses: docker/login-action@v2
      if: ${{ github.event_name == 'push' }}
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        build-args: |-
          FROM=ubuntu:${{ matrix.from }}
        cache-from: type=gha,scope=${{ matrix.from }}
        cache-to: type=gha,mode=max,scope=${{ matrix.from }}
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: |-
          quay.io/vexxhost/nova-ssh:${{ matrix.from }}
          quay.io/vexxhost/nova-ssh:${{ matrix.from }}-${{ github.sha }}

    - name: Promote image
      uses: akhilerm/tag-push-action@v2.0.0
      if: github.event_name == 'push' && matrix.from == 'jammy'
      with:
        src: quay.io/vexxhost/nova-ssh:${{ matrix.from }}
        dst: quay.io/vexxhost/nova-ssh:latest
