name: image

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    outputs:
      build-id: ${{ steps.build.outputs.build-id }}
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        id: build
        with:
          image-name: nova-ssh
          push: ${{ github.event_name != 'pull_request' }}
          save: true

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      - uses: depot/pull-action@v1
        with:
          build-id: ${{ needs.build.outputs.build-id }}
          tags: nova-ssh:test
      - uses: e1himself/goss-installation-action@3b8340a7c772f8064444f48b0df4c2a80d2e50fc # v1.3.0
      - run: dgoss run nova-ssh:test sleep infinity
